name: Deploy site

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'Build.fs'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up .NET Core 5 LTS
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: '5.0.100'

    - name: Install nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Create bundle
      run: |
        dotnet tool restore
        dotnet run bundle

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        publish_dir: ./publish